[package]
name = "fastq_10x"
version = "0.1.0"
authors = ["Patrick Marks <patrick@10xgenomics.com>"]

[dependencies]
ordered-float = "0.3.0"
flate2 = { version = "^1.0", features = ["zlib"], default-features = false }
serde_derive = "*"
serde_json = "*"
serde = "*"
serde_bytes = "*"
tempfile = "3"
rayon = "*"
log = "*"
bincode = "1.0.1"
fxhash = "0.2.1"
rand = ">=0.4"
itertools = ">=0.6"
failure = "*"
lz4 = "*"
bio = { git = "https://github.com/sreenathkrishnan/rust-bio" }

# Note you may need to use a local checkout rust-htslib to get around
# dependecy issues in the C htslib build. (bzip2 and lzma).
# rust-htslib = "0.19"
# rust-htslib = { path = "../rust-htslib" }

shardio = { git = "https://github.com/10XGenomics/rust-shardio.git" }
# bwa = { git = "https://github.com/10XGenomics/rust-bwa.git" }

# Switch back to crates.io once our PR is released
fastq = { git = "https://github.com/aseyboldt/fastq-rs.git"}

metric = { path = "../metric" }

[dev-dependencies]
time = "*"