[package]
name = "fastq_10x"
version = "0.2.0"
authors = ["Patrick Marks <patrick@10xgenomics.com>", "Sreenath Krishnan <sreenath.krishnan@10xgenomics.com>"]
edition = "2018"

[dependencies]
ordered-float = "1"
flate2 = { version = "^1.0", features = ["zlib"], default-features = false }
serde_derive = "*"
serde_json = "*"
serde = "*"
serde_bytes = "*"
bytes = { version = "0.5", features = ["serde"] }
failure = "*"
tempfile = "3"
glob = "0.3"
regex = "1"
lazy_static = "1"
csv = ">=1"

rayon = "*"
log = "*"
bincode = "1.0.1"
rand = "0.7"
rand_xorshift = "0.2"
itertools = ">=0.8"
lz4 = "*"
fastq = "^0.6"
bio = ">=0.29"
shardio = "0.7"

metric = { path = "../metric" }

[dev-dependencies]
time = "*"
file_diff = "1.0"
criterion = "0.2"
bincode = "*"
tempfile = "3.1.0"
psutil = ">=1.7"

[[bench]]
name = "benchmarks"
harness = false

[dev-dependencies.proptest]
version = "0.9"
default-features = false
# Enable all default features not known to break code coverage builds
features = ["default-code-coverage"]
