[package]
name = "fastq_10x"
version = "0.1.0"
authors = ["Patrick Marks <patrick@10xgenomics.com>"]

[dependencies]
ordered-float = "0.3.0"
flate2 = { version = "^1.0", features = ["zlib"], default-features = false }
serde_derive = "*"
serde_json = "*"
serde = "*"

#rust-htslib = "*"
rust-htslib = { path = "../../rust-htslib" }
#shardio = { git = "https://github.com/10XGenomics/rust-shardio.git" }
shardio = { path = "../../rust-shardio" }

bwa = { path = "../../rust-bwa" }

rayon = "*"
log = "*"
bincode = "*"
fxhash = "0.2.1"
rand = "*"
itertools = ">=0.6"

# Switch back to crates once PR is upstreamed.
fastq = { git = "https://github.com/pmarks/fastq-rs.git", rev = "e042ef2e59fff6365c1"}
failure = "*"