[package]
name = "fastq_10x"
version = "0.1.0"
authors = ["Patrick Marks <patrick@10xgenomics.com>", "Sreenath Krishnan <sreenath.krishnan@10xgenomics.com>"]
edition = "2018"

[dependencies]
ordered-float = "1"
flate2 = { version = "^1.0", features = ["zlib"], default-features = false }
serde_derive = "*"
serde_json = "*"
serde = "*"
serde_bytes = "*"
bytes = { version = "0.4", features = ["serde"] }
failure = "*"
tempfile = "3"
glob = "0.3"
regex = "1"
lazy_static = "1"

rayon = "*"
log = "*"
bincode = "1.0.1"
fxhash = "0.2.1"
rand = "0.5.0"
itertools = ">=0.6"
lz4 = "*"
fastq = "^0.6"
bio = { git = "https://github.com/sreenathkrishnan/rust-bio" }
shardio = "0.5.3"

metric = { path = "../metric" }

[dev-dependencies]
time = "*"
file_diff = "1.0"
criterion = "0.2"
bincode = "*"

[[bench]]
name = "benchmarks"
harness = false

[dev-dependencies.proptest]
version = "0.9"
default-features = false
# Enable all default features not known to break code coverage builds
features = ["default-code-coverage"]