[package]
name = "fastq_10x"
version = "0.1.0"
authors = ["Patrick Marks <patrick@10xgenomics.com>"]

[dependencies]
ordered-float = "0.3.0"
flate2 = "*"
serde = "*"
serde_derive = "*"

# Switch back to crates once PR is upstreamed.
fastq = { git = "https://github.com/pmarks/fastq-rs.git", rev = "e042ef2e59fff6365c1"}
failure = "*"
