name: Run tests

on:
  pull_request:
  push:
    branches:
      - master


jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.49.0
          components: rustfmt
      - name: Print cargo version
        run: rustup default 1.49.0 && cargo --version
      - name: Checkout Git repository
        uses: actions/checkout@master
      - name: Check Rust formatting
        run: cargo fmt -- --check
      - name: Build
        run: cargo build --release
      - name: Unit tests
        run: cargo test --release -- --nocapture
