name: Run tests

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read
  # Write permissions are required in order to produce annotations.
  checks: write

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.67.0
          components: rustfmt, clippy
      - name: Checkout Git repository
        uses: actions/checkout@master
      - name: Check Rust formatting
        run: cargo fmt -- --check
      - name: lint with clippy
        uses: 10XGenomics/clippy-check@main
        with:
          args: |
            --all-targets --
            -W clippy::wildcard_imports
            -W clippy::redundant_closure_for_method_calls
            -W clippy::enum_glob_use
            -A clippy::float_cmp
            -D clippy::unused_io_amount
            -W future_incompatible
            -W nonstandard_style
            -W rust_2018_compatibility
            -W rust_2021_compatibility
            -W unused
      - uses: EmbarkStudios/cargo-deny-action@v1
      - name: Build
        run: cargo build --release
      - name: Unit tests
        run: cargo test --release -- --nocapture
